# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


## Part 1 - Data Preprocessing

### Importing the dataset

In [11]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Churn_Modelling.csv')

## Description and Info of the Dataset

In [12]:
dataset.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


## Getting Features and Outcome

In [14]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [15]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [16]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [18]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [29]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [30]:
firstLayer = tf.keras.layers.Dense(units=6, activation='relu')
ann.add(firstLayer)

### Adding the second hidden layer

In [31]:


secondLayer = tf.keras.layers.Dense(units=6, activation='relu')
ann.add(secondLayer)

### Adding the output layer

In [33]:
outputLayer = tf.keras.layers.Dense(units=1, activation='sigmoid')
ann.add(outputLayer)

## Part 3 - Training the ANN

### Compiling the ANN

In [34]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6710 - accuracy: 0.5975
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4807 - accuracy: 0.8006
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4482 - accuracy: 0.8067
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4344 - accuracy: 0.8109
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4255 - accuracy: 0.8126
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accuracy: 0.8185
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4096 - accuracy: 0.8231
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4002 - accuracy: 0.8306
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3865 - accuracy: 0.8409
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3732 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [53]:
def showPrediction(predicition):
  shouldWeSayGoodBye = prediction > 0.5
  result = "definitely" if shouldWeSayGoodBye == True else "not"
  probability = str(100 - prediction[0] * 100)
  print("We should " + result + " say goodbye to the customer. The probality of the customer staying is " + probability + "%" )

In [54]:
creditScore = 600
gender = 1
age = 40
tenure = 3
balance = 60000
products = 2
haveCreditCard = 1
activeMember = 1
estimatedSalary = 50000
target = [[1, 0, 0, creditScore, gender, age, tenure, balance, products, haveCreditCard, activeMember, estimatedSalary]]
target = sc.transform(target)
prediction = ann.predict(target)
showPrediction(prediction[0])

We should not say goodbye to the customer. The probality of the customer staying is [97.89198]%


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [55]:
y_pred = ann.predict(X_test)
for prediction in y_pred:
  showPrediction(prediction)

We should not say goodbye to the customer. The probality of the customer staying is 80.50497770309448%
We should not say goodbye to the customer. The probality of the customer staying is 62.02417314052582%
We should not say goodbye to the customer. The probality of the customer staying is 79.7300636768341%
We should not say goodbye to the customer. The probality of the customer staying is 95.30465006828308%
We should not say goodbye to the customer. The probality of the customer staying is 94.93864476680756%
We should definitely say goodbye to the customer. The probality of the customer staying is 14.76401686668396%
We should not say goodbye to the customer. The probality of the customer staying is 98.80108535289764%
We should not say goodbye to the customer. The probality of the customer staying is 88.54421973228455%
We should not say goodbye to the customer. The probality of the customer staying is 68.64285469055176%
We should definitely say goodbye to the customer. The probality of 

In [62]:
whoStays = [x for x in y_pred if x > 0.5]
whoLeaves = [x for x in y_pred if x <= 0.5]
totalStaying = len(whoStays)
totalLeaving = len(whoLeaves)
print("In total " + str(totalStaying) + " will stay and " + str(totalLeaving) + " will leave.")

In total 288 will stay and 1712 will leave.


### Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 213  192]]


0.8605